spring.application.name=ProductService
server.port=8082
spring.kafka.producer.acks=all
spring.kafka.producer.properties.min.insync.replicas=2
spring.kafka.partition.count=3
spring.kafka.replica.count=3
#spring.kafka.producer.retries=3
#spring.kafka.producer.properties.retry.backoff.ms=1000

# delivery timeout = requestTimeout+lingerTimeout(should be greater or equal to)
spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.linger.ms=5
spring.kafka.producer.bootstrap-servers=localhost:9092,localhost:9094,localhost:9096
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5

# ===============================
# H2 Database
# ===============================
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 Console
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

product.commands.topic.name=products-commands
product.events.topic.name=products-events
spring.kafka.consumer.group-id=product-saga
spring.kafka.consumer.properties.spring.json.trusted.packages=com.kafka.saga.CoreService.*